import React from 'react';
import { HelpCircle, ArrowDownRight, Layers, Sparkles, Scale } from 'lucide-react';
import { CounterfactualScenario } from '../../types';
import { Card } from '../common/Card';

interface CounterfactualPanelProps {
  scenarios: CounterfactualScenario[];
  currentScore: number;
  className?: string;
}

export const CounterfactualPanel: React.FC<CounterfactualPanelProps> = ({
  scenarios,
  currentScore,
  className = '',
}) => {
  return (
    <Card
      title="Counterfactual Causal Analysis"
      subtitle="Recomputed risk scores showing the exact impact of omitting individual observable signals"
      badge={
        <div className="flex items-center gap-1.5 px-2 py-0.5 rounded border border-neutral-300 dark:border-neutral-700 bg-neutral-100 dark:bg-neutral-900 text-[10px] font-mono font-semibold">
          <Scale className="w-3 h-3" />
          <span>TRUE RECOMPUTATION ENGINE</span>
        </div>
      }
      className={className}
    >
      <div className="space-y-4">
        {/* Baseline Header */}
        <div className="flex flex-wrap items-center justify-between p-3.5 rounded-lg bg-neutral-100 dark:bg-neutral-900 border border-neutral-200 dark:border-neutral-800 text-xs">
          <div>
            <span className="text-[10px] font-mono uppercase tracking-wider text-neutral-500 block">
              Active Assessment State
            </span>
            <span className="font-bold text-neutral-950 dark:text-white text-sm">
              Current Review Priority: {currentScore} points
            </span>
          </div>
          <span className="text-[11px] font-mono text-neutral-500 max-w-sm text-right">
            Values generated by dynamically re-running the temporal multi-signal scoring model.
          </span>
        </div>

        {/* Scenarios Table */}
        <div className="space-y-2">
          {scenarios.map((sc, idx) => (
            <div
              key={idx}
              className="p-3.5 rounded-lg border border-neutral-200 dark:border-neutral-850 bg-white dark:bg-neutral-950 hover:border-neutral-400 dark:hover:border-neutral-700 transition-all flex flex-col sm:flex-row sm:items-center justify-between gap-3 text-xs"
            >
              <div className="space-y-1 max-w-xl">
                <div className="flex items-center gap-2">
                  <span className="font-bold text-neutral-950 dark:text-white tracking-tight">
                    {sc.label}
                  </span>
                  {sc.delta > 0 && (
                    <span className="inline-flex items-center text-[10px] font-mono font-bold px-1.5 py-0.2 rounded bg-neutral-200 dark:bg-neutral-800 text-black dark:text-white">
                      -{sc.delta} PTS
                    </span>
                  )}
                </div>
                <p className="text-neutral-600 dark:text-neutral-400 text-[11px] leading-relaxed">
                  {sc.explanation}
                </p>
              </div>

              <div className="flex items-center gap-3 sm:flex-shrink-0 self-end sm:self-center font-mono">
                <div className="text-right">
                  <span className="text-[10px] text-neutral-400 block">RECALCULATED SCORE</span>
                  <strong className="text-sm text-black dark:text-white">{sc.scoreWithoutSignal}</strong>
                </div>
                <div className="w-16 h-2 bg-neutral-200 dark:bg-neutral-800 rounded-full overflow-hidden">
                  <div
                    className="h-full bg-black dark:bg-white rounded-full transition-all"
                    style={{ width: `${Math.min(100, sc.scoreWithoutSignal)}%` }}
                  />
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </Card>
  );
};
