import React from 'react';
import { ArrowDownRight, Scale } from 'lucide-react';
import { CounterfactualScenario } from '../../types';
import { Card } from '../common/Card';

interface CounterfactualPanelProps {
  scenarios: CounterfactualScenario[];
  currentScore: number;
  className?: string;
}

export const CounterfactualPanel: React.FC<CounterfactualPanelProps> = ({
  scenarios,
  currentScore,
  className = '',
}) => {
  return (
    <Card
      title="Counterfactual causal analysis"
      subtitle="Recomputed review priority showing the exact impact of omitting each observable signal"
      badge={
        <span className="data inline-flex items-center gap-1.5 rounded-full border border-slate-200 bg-slate-50 px-2.5 py-1 text-[11px] text-slate-600 whitespace-nowrap">
          <Scale className="w-3 h-3" />
          Recomputation engine
        </span>
      }
      className={className}
    >
      <div className="space-y-4">
        {/* Baseline */}
        <div className="flex flex-wrap items-center justify-between gap-3 rounded-md border border-slate-200 bg-slate-50 px-4 py-3">
          <div>
            <span className="eyebrow">Active assessment state</span>
            <div className="mt-1 flex items-baseline gap-1.5">
              <span className="data text-[20px] font-semibold leading-none text-slate-900">
                {currentScore}
              </span>
              <span className="text-[12.5px] text-slate-500">points review priority</span>
            </div>
          </div>
          <p className="text-[12px] text-slate-500 max-w-sm leading-relaxed">
            Values generated by re-running the temporal multi-signal scoring model with the
            indicated signal removed.
          </p>
        </div>

        {/* Scenarios */}
        <div className="space-y-2">
          {scenarios.map((sc, idx) => (
            <div
              key={idx}
              className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 rounded-md border border-slate-200 bg-white px-4 py-3.5 transition-colors hover:border-slate-300"
            >
              <div className="space-y-1.5 max-w-xl">
                <div className="flex items-center gap-2">
                  <span className="text-[13.5px] font-semibold text-slate-900">{sc.label}</span>
                  {sc.delta > 0 && (
                    <span className="inline-flex items-center gap-1 rounded-[3px] bg-slate-100 px-1.5 py-0.5 data text-[11px] font-medium text-slate-700">
                      <ArrowDownRight className="w-3 h-3" />
                      {sc.delta} pts
                    </span>
                  )}
                </div>
                <p className="text-[12.5px] text-slate-600 leading-relaxed">{sc.explanation}</p>
              </div>

              <div className="flex items-center gap-3 sm:flex-shrink-0 self-end sm:self-center">
                <div className="text-right">
                  <span className="eyebrow">Recalculated</span>
                  <div className="data text-[15px] font-semibold text-slate-900 mt-0.5">
                    {sc.scoreWithoutSignal}
                  </div>
                </div>
                <div className="w-20 h-1.5 rounded-full bg-slate-200 overflow-hidden">
                  <div
                    className="h-full rounded-full bg-brand-700 transition-[width] duration-300"
                    style={{ width: `${Math.min(100, sc.scoreWithoutSignal)}%` }}
                  />
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </Card>
  );
};
